### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by danielzgtg**
This adds a license as discussed during the call. This properly clarifies the licensing situation. The terms were chosen to grant us more rights than strangers during capstone so evaluation is not interfered with.

### CODE REVIEW

**Review by jodiqiao — APPROVED** [review]
Great work, thanks.

**Comment by jodiqiao** [comment]
Merge license info for README

**Comment by Daanish-Khan** [comment]
Lgtm

**Comment by philippe-gagne** [comment]
Approved.

**Pull request merged**
